### ISSUE TITLE
Manage hardware automatically or add instructions to readme

### ISSUE THREAD

**Issue by DavHau** [nix-community/nixos-anywhere#58] opened 2023-02-04 04:21 UTC
**Is your feature request related to a problem? Please describe.**

On my first use of nixos-anywhere, the remote machine did not boot anymore.

**Describe the solution you'd like**

As a user I'm not interested to deal with hardware specifics. I just want a working system. Any solution that requires zero interaction is preferred.

**Describe alternatives you've considered**

### Alternative 1
Mention the necessity of a hardware-configuration in the docs, and describe how to generate one.

### Alternative 2
Include all-hardware.nix from nixpkgs by default

### Alternative 3
Generate a hardware-configuration for my system by default and include it automatically + notify user about it.

**Additional context**

If we generate a hardware-configuration.nix automatically, the question would be, how do we include it.
As currently users have to expose their system via `nixosConfigurations`, we could use ``:

```command
nix-repl> nixosConfigurations.my-machine.extendModules {modules=[./hardware-configuration.nix];}
```

The problem with that approach is, that including the hardware config becomes an implementation detail of nixos-anywhere, and the setup will break again as soon as another tool will be used for future deployments.

**Comment by phaer** [comment] 2023-02-07 06:25
A typical, auto-generated `hardware-configuration.nix` may contain a few different things. As `fileSystems` can be generated by diskos nixos module, so I believe we are primarily talking about (available) kernel modules, firmware and things like 
`powerManagement.cpuFreqGovernor`,   hardware.cpu.intel.updateMicrocode`, `hardware.video.hidpi.enable` and so on?

> The problem with that approach is, that including the hardware config becomes an implementation detail of nixos-anywhere, and the setup will break again as soon as another tool will be used for future deployments.

Yes, if we go it that way, we would probably have to ask users to download the generated hardware-configuration via ssh or add a flag to so from nixos-anywhere itself. Not really a fan of this approach, but we would keep this feature optional anyways as we also accepting store paths of a system closure, not only flake attrs.

Maybe just referring to https://github.com/NixOS/nixos-hardware here would be a good first step?

**Comment by Mic92** [comment] 2023-02-07 11:35
We have already started documenting a workflow for setting up bare metal machines, which will hopefully address this. In long-term we should thing of workflows which can generate hardware configuration.

**Comment by sweenu** [comment] 2024-03-22 21:23
Is there really no way to generate the hardware config from a non-NixOS distro ? It'd be so practical to be able to run a remote command to generate the hardware config without having to go through the kexec method.

**Comment by DavHau** [comment] 2024-03-23 03:08
Yes, you can:

```
apt install nix
nix-shell -p nixos-install-tools
nixos-generate-config --show-hardware-config
```

IMO it is a design mistake in upstream NixOS to require a hardware config at all in order to activate the right firmware and kernel modules.

Any other existing distro simply boots without requiring these things to be specified. Also our installer iso simply boots an any machine which shows that it is possible to have defaults that work on any machine.

These defaults (eg. all-hardware.nix) should just be included by default on any system.

Generating a hardware-config.nix could still be done manually by people who want to minimize their closure, after the system is already installed. Closure optimization should be the only purpose of the hardware-config and we should not sacrifice UX in favor of closure as it's done right now.

**Comment by Mic92** [comment] 2024-03-23 19:39
> Yes, you can:
> 
> ```
> apt install nix
> nix-shell -p nixos-install-tools
> nixos-generate-config --show-hardware-config
> ```
> 
> IMO it is a design mistake in upstream NixOS to require a hardware config at all in order to activate the right firmware and kernel modules.

Other distros enable firmware in the initrd by detecting what hardware is available on the machine. This means you no longer can build your system fully in a reproducible way since it requires information about the hardware.

**Comment by Mic92** [comment] 2024-03-23 19:42
> Is there really no way to generate the hardware config from a non-NixOS distro ? It'd be so practical to be able to run a remote command to generate the hardware config without having to go through the kexec method.

This is not the only reason we do kexec. It's also so that we no longer depend on the root filesystem and can reformat everything (also that we have our own kernel for things like zfs/bcachefs). If you don't need this feature you can use https://github.com/elitak/nixos-infect

**Comment by Mic92** [comment] 2024-03-23 19:44
> Generating a hardware-config.nix could still be done manually by people who want to minimize their closure, after the system is already installed. Closure optimization should be the only purpose of the hardware-config and we should not sacrifice UX in favor of closure as it's done right now.

nixos-anywhere doesn't impose restriction of what people put in their nixos configuration. That means you can include all-hardware.nix if you want.

**Comment by Mic92** [comment] 2024-03-23 19:46
The documentation mentions that one needs to generate a hardware configuration upfront. https://github.com/nix-community/nixos-anywhere/blob/main/docs/quickstart.md#steps-required-to-run-nixos-anywhere
Including some default hardware is out of scope. This is more of a NixOS problem as we don't change alter the behavior here.

**Closed by Mic92** 2024-03-23 19:46 UTC
Labels: enhancement

**Comment by DavHau** [comment] 2024-03-24 03:06
Of course it does not make sense to include anything automatically in a non-transparent manner. But the quick start could be vastly simplified by just providing an example with all-hardware included and moving the whole section about generating your own hardware config towards the end, when nixos is already installed.

**Comment by Mic92** [comment] 2024-03-24 05:59
What do you do with conflicting options? I.e. it's not possible to have both amd or intel microcode since both need to be the first entry in the initrd. It might be acceptable to do this with installers but for installed systems, people will miss out on security updates provided from these options. 

The other problem is that even all-hardware.nix is still not complete and the dynamic scan can find more hardware modules such as special nvme modules on rockchips and SAS controllers. These modules are commonly not part of our NixOS installer because no one is booting installer from those. It would be than also terrible UX when suggest non-working configuration instead of just running one extra step to get it working.

**Comment by Mic92** [comment] 2024-03-24 06:24
Long-term solution would be more automation to make the generation of device specific configuration more convenient. I started the discussion with a project regarding this. I cannot put a time-line on it, when we would get to it.
